[tools]
act = "0.2.84"
actionlint = "1.7.10"
azure-cli = "2.82.0"
gitleaks = "8.24.3"
go = "1.25.6"
golangci-lint = "2.8.0"
goreleaser = "2.13.3"
pre-commit = "4.5.1"
trivy = "0.68.2"
yamlfmt = "0.21.0"
